### PR TITLE
updates dependency to Azure SDKs and Kafka API

### PR DESCRIPTION
**Pull request by sv3ndk**
Hi, 

While experimenting with this kafka Connect connector, I noted that some libraries could be updated

=> I updated the sbt build as follows

 - updated Azure SDK IOT from 1.0.12 to 1.4.22
 - updated Azure Event Hub SDK lib from 0.9.0 to 0.14.0
 - updated kafka API from 0.10.0.1 to  0.10.2.1

Also: since it seems that some SDK classes have been moved, I updated the packages name to align on that. 

All UT still pass and I also tested it successfully to forward messages from my local Kafka cluster to my IoTHub instance.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/toketi-kafka-connect-iothub/7)

### CODE REVIEW

**Comment by sv3ndk** [comment]
Hi all, 

Any news from this? Once this one gets merged, a next step could be to add support for sending Avro records to IotHub, as opposed to only allowing JSON as currently implemented. 

I tested and documented [how to send avro records to Eventhub from scala](https://svendx4f.github.io/sending-avro-records-from-scala-to-azure-eventhub-over-amqp.html) on my blog yesterday, and I am pretty sure it works the same way for IotHub. 

What do you think?

**Comment by varunpuranik** [comment]
Hi, 
Thanks for the changes, they look good. I will do some testing on my end and then approve the PR.

**Comment by varunpuranik** [comment]
I tested the changes, and they look good. Can you please make one more change - can you update the Readme for source connector to use com.microsoft.azure.iot.kafka.connect.source.IotHubSourceConnector as the connector class?

**Comment by sv3ndk** [comment]
Done :) 
I also updated the links to the latest Confluent platform in the other Readme.

**Review by varunpuranik — APPROVED** [review]
Looks good, thanks for the changes. I will merge the PR.

**Pull request merged**
